config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import contact, StudentListView, StudentDetailView, StudentCreateView, StudentUpdateView, \
    StudentDeleteView, toggel_activity

app_name = MainConfig.name

urlpatterns = [
    path('', StudentListView.as_view(), name='student_list'),
    # path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('view/<int:pk>/', StudentDetailView.as_view(), name='view_student'),
    path('create/', StudentCreateView.as_view(), name='create_student'),
    path('update/<int:pk>', StudentUpdateView.as_view(), name='update_student'),
    path('delete/<int:pk>', StudentDeleteView.as_view(), name='delete_student'),
    path('activity/<int:pk>', toggel_activity, name='activity_student'),


]

materials/urls.py
from django.urls import path

from materials.apps import MaterialsConfig
from main.views import contact, StudentListView, StudentDetailView
from materials.views import MaterialCreateView, MaterialListView, MaterialDetailView, MaterialUpdateView, \
    MaterialDeleteView

app_name = MaterialsConfig.name

urlpatterns = [

    path('create/', MaterialCreateView.as_view(), name='create'),
    path('', MaterialListView.as_view(),  name='list'),
    path('view/<int:pk>/', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', MaterialUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MaterialDeleteView.as_view(), name='delete'),
]

materials/models.py
from django.db import models

class Material(models.Model):
    title = models.CharField(max_length=150, verbose_name='название материала')
    body = models.TextField(verbose_name='содержимое')

    views_count = models.IntegerField(default=0, verbose_name='просмотры') # Для фиксации просмотров
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return self.title


    class Meta:
        verbose_name = 'материал'
        verbose_name_plural = 'материалы'

materials/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse

from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from pytils.translit import slugify

from materials.models import Material


class MaterialCreateView(CreateView):
    model = Material
    fields = ('title', 'body')
    success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)



class MaterialUpdateView(UpdateView):
    model = Material
    fields = ('title', 'body')
    # success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('materials:view',args=[self.kwargs.get('pk')]) # После сохранения изменение идет перенаправление на измененный материал


class MaterialListView(ListView):
    model = Material

    def get_queryset(self, *args, **kwargs):  # Переопределение. Выводит только активные публикации
        queryset = super().get_queryset(*args, **kwargs)  # В переменную загружаем данные из родительского
        queryset = queryset.filter(is_published=True)  # Через фильтр только активные

        return queryset


class MaterialDetailView(DetailView):
    model = Material

    def get_object(self,
                   queryset=None):  # Счетчик количества просмотров. При каждом обращении к метериалу счетчик увеличивается на один
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        return self.object


class MaterialDeleteView(DeleteView):
    model = Material
    success_url = reverse_lazy('materials:list')

materials/templates/materials/material_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}

                                <p>Хотите удалить материал "{{object.title}}"?</p>
                                <button type="submit" class="btn btn-success"> Подтвердить</button>
                                <a href="{% url 'materials:list' %}" class= "btn btn-danger">Отмена удаления</a>
                            </form>
                        </div>
                    </div>
                </div>
        </div>
    </div>

{% endblock %}

materials/templates/materials/material_detail.html
{% extends 'main/base.html'%}



{% block content%}

    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Материал {{ object.title }}  /слаг ({{  object.slug}})/
                        </h3>
                    </div>
                    <div class="card-body">
                        <p>
                            {{ object.body }}
                        </p>
                    </div>
                    <div class="card-footer">
                        Просмотры: {{ object.views_count }}
                    </div>

                </div>
                <p>
                <div class="col-12">
                    <a class="btn btn-outline-primary" href="{% url 'materials:list' %}">назад к материалам</a>
                </div>
                </p>
            </div>

        </div>

    </div>

<!--<div class="col">-->
<!--              <div class="card shadow-sm">-->
<!--&lt;!&ndash;                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>&ndash;&gt;-->
<!--                <div class="card-body">-->
<!--                  <p class="card-text">-->
<!--                       <p class="card-text">Имя:   {{ object.first_name }} </p>-->
<!--                    <p class="card-text">Фамилия:  {{ object.last_name }}</p>-->
<!--                    <p class="card-text"> Статус учится или нет:  {{ object.is_active }}</p>-->
<!--                  </p>-->
<!--                  <div class="d-flex justify-content-between align-items-center">-->
<!--                    <div class="btn-group">-->
<!--                    <a href="{% url 'main:index' %}" type="button" class="btn btn-sm btn-outline-secondary">Вернуться на главную</a>-->
<!--&lt;!&ndash;                           <button type="button" class="btn btn-sm btn-outline-secondary">View</button>&ndash;&gt;&ndash;&gt;-->
<!--&lt;!&ndash;                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>&ndash;&gt;-->
<!--                    </div>-->
<!--&lt;!&ndash;                    <small class="text-body-secondary">9 mins</small>&ndash;&gt;-->
<!--                  </div>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->







{% endblock %}

materials/templates/materials/material_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">
                                    {% if object %}
                                        Сохранить
                                    {% else %}
                                        Создать
                                    {% endif %}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
        </div>
    </div>

{% endblock %}

materials/templates/materials/material_list.html
{% extends 'main/base.html' %}

{% block content%}
        <div class="col-12 mb5">
            <a class="btn btn-outline-primary" href="{% url 'materials:create' %}">Добавить материал</a>
        </div>
          {% for object in object_list %}
            <div class="col">
              <div class="card shadow-sm">
<!--                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>-->
                <div class="card-body">
                  <p class="card-text">

                        {{ object | title }}  {{object.pk}}

                  </p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'materials:view' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Подробнее о материале</a>
                        <a href="{% url 'materials:edit' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Редактирование</a>
                        <a href="{% url 'materials:delete' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Удаление</a>
<!--                           <button type="button" class="btn btn-sm btn-outline-secondary">View</button>&ndash;&gt;-->
<!--                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>-->
                    </div>

                  </div>
                </div>
              </div>
            </div>

          {% endfor %}
{% endblock %}