config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import contact, StudentListView, StudentDetailView, StudentCreateView, StudentUpdateView, \
    StudentDeleteView, toggel_activity

app_name = MainConfig.name

urlpatterns = [
    path('', StudentListView.as_view(), name='student_list'),
    # path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('view/<int:pk>/', StudentDetailView.as_view(), name='view_student'),
    path('create/', StudentCreateView.as_view(), name='create_student'),
    path('update/<int:pk>', StudentUpdateView.as_view(), name='update_student'),
    path('delete/<int:pk>', StudentDeleteView.as_view(), name='delete_student'),
    path('activity/<int:pk>', toggel_activity, name='activity_student'),


]

main/models.py
from django.db import models

# Create your models here.
NULLABLE = {'null': True, 'blank': True}


class Student(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    avatar = models.ImageField(upload_to='students/', verbose_name='аватар', **NULLABLE)

    email = models.EmailField(max_length=150, verbose_name='email', unique=True, **NULLABLE)

    is_active = models.BooleanField(default=True, verbose_name='статус обучения')

    def __str__(self):
        return f'{self.first_name}  {self.last_name}'

    class Meta:
        verbose_name = 'студент'
        verbose_name_plural = 'студенты'
        ordering = ('last_name', )

main/forms.py
from django import forms

from main.models import Student


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "is_active":
                field.widget.attrs['class'] = 'form-control'

class StudentForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Student
        fields = ('first_name', 'last_name', 'avatar', 'is_active', 'email',)
        # fields = '__all__',
        # exclude  = ( 'is_active',)






    def clean_email(self):
        cleaned_data = self.cleaned_data['email']

        if 'sky.pro' not in cleaned_data:
            raise forms.ValidationError('Почта должна относиться к домену sky.pro')

        return cleaned_data

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template.defaultfilters import lower
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from main.forms import StudentForm
from main.models import Student


def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        print(f'{name}, ({email}) сообщение:/{message}/')

    context = {
        'title': 'Контакты',
        'description': 'контактная информация и форма обратной связи',
    }

    return render(request, 'main/contact.html', context)


class StudentCreateView(CreateView):
    model = Student
    form_class = StudentForm
    # fields = ('first_name', 'last_name', 'avatar', 'is_active')
    success_url = reverse_lazy('main:student_list')


class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm
    # fields = ('first_name', 'last_name', 'avatar', 'is_active')
    success_url = reverse_lazy('main:student_list')


class StudentListView(ListView):
    model = Student


# def index(request):
#     students_list = Student.objects.all()
#     context = {
#         'object_list': students_list,
#         'title': 'Главная',
#         'description': 'описание главной страницы',
#     }
#
#     return render(request, 'main/student_list.html', context)


class StudentDetailView(DetailView):
    model = Student
    # template_name = 'main/student_detail.html'

# def view_student(request, pk):
#     student_item = get_object_or_404(Student, pk=pk)
#     context = {
#         'object': student_item,
#         'title': 'Информация о студенте ',
#         'description': f'{student_item.first_name} {student_item.last_name}',
#     }
#     return render (request, 'main/student_detail.html', context)

class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('main:student_list')

def toggel_activity(request, pk): #реализация активации/деактивации студента
    student_item= get_object_or_404(Student, pk=pk)
    if student_item.is_active:
        student_item.is_active = False
    else:
        student_item.is_active = True

    student_item.save()

    return redirect(reverse('main:student_list'))

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{{ title }}</title>





    <!-- Bootstrap core CSS -->
<link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">




    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


  </head>
  <body>

<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-muted">{{ title }}</h4>
          <h1  class="text-white"> {{ description| title }}</h1>

        </div>
        {% include 'main/includes/inc_main_menu.html' %}
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Album</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h3 class="fw-light">{{ title }} </h3>
        <h1 class="text-muted">{{ description| title }}</h1>
<!--          <a href="#" class="btn btn-primary my-2">Main call to action</a>-->
<!--          <a href="#" class="btn btn-secondary my-2">Secondary action</a>-->
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {% block content %}
        {% endblock %}

      </div>
    </div>
  </div>

</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p>
       {% include 'main/includes/inc_main_menu.html' %}
<!--      <li><a href="{% url 'main:student_list' %}" class="text-blue">Главная</a></li>-->
<!--      <li><a href="{% url 'main:contact' %}" class="text-blue">Контакты</a></li>-->
    </p>
    <p class="mb-1"> Улыбайтесь! Людям это нравится! &copy; Студия DG {% now 'Y' %} год. </p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>


    <script src="{% static 'js/bootstrap.bundle.min.js '%}" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


  </body>
</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}

{% block content %}


        <div class="col">
          <div class="card shadow-sm">


            <div class="card-body">
              <h2>Наш адрес:</h2>
              <p class="card-text">
                    Офис МСК<br>
                    Офис СПБ<br>

              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">

                </div>

              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">


            <div class="card-body">
              <h2>  Напишите нам  </h2>
                    <form method="post">
                        {% csrf_token %}
                        <input class="form-control mb-2" name="name"/>
                        <input class="form-control mb-2" name="email"/>
                        <textarea class="form-control mb-2" name="message"></textarea>
                        <button type="submit" class="btn btn-primary form-control mb-2">Отправить</button>


                    </form>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">

                </div>

              </div>
            </div>
          </div>
        </div>

{% endblock %}

main/templates/main/student_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}

                                <p>Хотите удалить студента "{{object.first_name}} {{object.last_name}}"?</p>
                                <button type="submit" class="btn btn-success"> Подтвердить</button>
                                <a href="{% url 'main:student_list' %}" class= "btn btn-danger">Отмена удаления</a>
                            </form>
                        </div>
                    </div>
                </div>
        </div>
    </div>

{% endblock %}

main/templates/main/student_detail.html
{% extends 'main/base.html' %}



{% block content%}
<div class="card">
    <img src="/media/{{ object.avatar }}">
</div>
                <div class="card">
                    <div class="card-header">
                        <h6 class="card-title">
                        Информация о студенте
                        </h6>

                    </div>
                    <div class="card-body">



                        <table class="table">

                            <tr>
                                <td>Имя</td>
                                <td>{{object.first_name}}</td>
                            </tr>
                            <tr>
                                <td>Фамилия</td>
                                <td>{{object.last_name}}</td>
                            </tr>
                            <tr>
                                <td>Почта</td>
                                <td>{{object.email}}</td>
                            </tr>
                        </table>



                    </div>
                    <div class="card-footer">
                        <div class="btn-group">

                        <a href="{% url 'main:update_student' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary"> Редактирование</a> <
                        <a href="{% url 'main:student_list' %}" type="button" class="btn btn-sm btn-outline-secondary"> К списку студентов</a>

                         </div>
                        </div>


                </div>



                <div class="card">
                    <div class="card-header">
                        <h6 class="card-title">
                            Предметы студента
                            </h6>

                    </div>
                    <div class="card-body">
<!--                        {{ formset.management_form }}-->
<!--                        {% for form in formset.forms %}-->
<!--                           {{ form.as_p }}-->
<!--                                {% if not forloop.last %}-->
<!--                                    <hr> # горизонтальная линия-->
<!--                                {% endif %}-->
<!--                        {% endfor %}-->
                        <ul>
                            {% for subject in subjects %}
                            <li>{{subject}}</li>
                            {%endfor%}
                        </ul>
                    </div>
                    <div class="card-footer"></div>

                </div>







{% endblock %}

main/templates/main/student_form.html
{% extends 'main/base.html'  %}}

{% block content %}

<!--    <div class="col-12 mb5">-->
<!--        <div class="row">-->
<!--           <div class="col-6 mb5">-->
<!--               <div class="card">-->
<!--                   <div class="card-body">-->
<!--                       <form method="post" enctype="multipart/form-data">-->
<!--                           {% csrf_token %}-->
<!--                           {{form.as_p}}-->
<!--                           <button type="submit" class="btn btn-sm btn-outline-secondary">Сохранить</button>-->
<!--                           <a href="{% url 'main:student_list' %}" type="button" class="btn btn-sm btn-outline-secondary"> назад</a>-->
<!--                       </form>-->

<!--                   </div>-->
<!--               </div>-->


<!--        </div>-->
<!--    </div>-->

<div class="col-6 mb5">
    <div class="card-header">
        <h4 class="card-title">Добавление студента</h4>
    </div>
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-sm btn-outline-secondary">Сохранить</button>
            <a href="{% url 'main:student_list' %}" type="button" class="btn btn-sm btn-outline-secondary"> назад</a>

        </form>
    </div>
    <div class="card-footer"></div>

</div>

{% endblock %}

main/templates/main/student_list.html
{% extends 'main/base.html' %}

{% block content %}
 <div class="col-12 mb-5">
            <a class="btn btn-outline-primary" href="{% url 'main:create_student' %}">Добавить студента</a>
         </div>

        {% for object in object_list %}

        <div class="col">
          <div class="card shadow-sm">
            <img src="/media/{{ object.avatar }}">
            <div class="card-body">
              <p class="card-text">
                  {% if object.is_active %}
                      {{ object|title }}
                  {% else %}
                      <span class="text-muted">{{ object|title }}</span>
                  {% endif %}

              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'main:view_student' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary"> View</a>
                  <a href="{% url 'main:update_student' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                  <a href="{% url 'main:delete_student' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary"> Delete</a>

                </div>
                  {% if object.is_active %}
                    <a href="{% url 'main:activity_student' object.pk %}" type="button" class="btn btn-sm btn-outline-warning"> Deactivation</a>
                  {% else %}
                  <a href="{% url 'main:activity_student' object.pk %}" type="button" class=""> Activation</a>
                  {% endif %}
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

{% endblock %}